//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRanwa.EOD.Chart.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PortalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRanwa.EOD.Chart.Business.PortalRes", typeof(PortalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details retrieve failed..
        /// </summary>
        internal static string Message_UserDetailsRetrieveFailed {
            get {
                return ResourceManager.GetString("Message_UserDetailsRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email already verified..
        /// </summary>
        internal static string Message_UserEmailAlreadyVerified {
            get {
                return ResourceManager.GetString("Message_UserEmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email verification resending failed..
        /// </summary>
        internal static string Message_UserEmailResendFailed {
            get {
                return ResourceManager.GetString("Message_UserEmailResendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email verification resend successfully..
        /// </summary>
        internal static string Message_UserEmailResendSuccess {
            get {
                return ResourceManager.GetString("Message_UserEmailResendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email verification failed..
        /// </summary>
        internal static string Message_UserEmailVerificationFailed {
            get {
                return ResourceManager.GetString("Message_UserEmailVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email verification success..
        /// </summary>
        internal static string Message_UserEmailVerificationSuccess {
            get {
                return ResourceManager.GetString("Message_UserEmailVerificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login credentials invalid..
        /// </summary>
        internal static string Message_UserLoginCredentialsIncorrect {
            get {
                return ResourceManager.GetString("Message_UserLoginCredentialsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email not verified..
        /// </summary>
        internal static string Message_UserLoginEmailNotVerified {
            get {
                return ResourceManager.GetString("Message_UserLoginEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login failed..
        /// </summary>
        internal static string Message_UserLoginFailed {
            get {
                return ResourceManager.GetString("Message_UserLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login successful..
        /// </summary>
        internal static string Message_UserLoginSuccess {
            get {
                return ResourceManager.GetString("Message_UserLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile details updated failed..
        /// </summary>
        internal static string Message_UserProfileUpdateFailed {
            get {
                return ResourceManager.GetString("Message_UserProfileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile details updated successfully..
        /// </summary>
        internal static string Message_UserProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("Message_UserProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration failed..
        /// </summary>
        internal static string Message_UserRegistrationFailed {
            get {
                return ResourceManager.GetString("Message_UserRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully..
        /// </summary>
        internal static string Message_UserRegistrationSuccess {
            get {
                return ResourceManager.GetString("Message_UserRegistrationSuccess", resourceCulture);
            }
        }
    }
}
